export default {
  gallery: document.querySelector('.gallery'),
  modal: document.querySelector('#modal-movie__description'),
  input: document.querySelector('.header__input'),
  searchBtn: document.querySelector('.header__button'),
  homeBtn: document.querySelector('[data-name="home"]'),
  libraryBtn: document.querySelector('[data-name="library"]'),
  headerBack: document.querySelector('.header'),
  headerForm: document.querySelector('.header__form'),
  watchedBtn: document.querySelector('[data-name="watched"]'),
  queueBtn: document.querySelector('[data-name="queue"]'),
  body: document.querySelector('body'),
  themeSwitcher: document.querySelector('#theme-switch-toggle'),
  footerLink: document.querySelector('.footer__link'),
  clearInputBtn: document.querySelector('.clear-input'),
  paginationBar: document.querySelector('#pagination'),
  trendingBtn: document.querySelector('.trending-btn'),
  popularBtn: document.querySelector('.popular-btn'),
  topRatedBtn: document.querySelector('.toprated-btn'),
  upcomingBtn: document.querySelector('.upcoming-btn'),
  actors: document.querySelector('.actors'),
  closeFooter: document.querySelector('.close'),
  footerModal: document.querySelector('.footer_modal'),
  galleryButtons: document.querySelectorAll('.gallery-btn'),
  selectionButtons: document.querySelector('.selection-buttons')
};

